### ISSUE TITLE
Interest in a PR for Windows support?

### ISSUE THREAD

**Issue by fredvisser** [ftpsolutions/python-third-party-license-file-generator#1]
The current version has a handful of minor issues (e.g. subprocess.Popen(…) has platform specific arguments, some path concatenation using '/', and string parsing that fails with invalid characters) that prevent the tool from running correctly on Windows. 

Would you be interested in an PR that fixes these?

**Comment by initialed85** [comment]
I'm not actually a part of the owning organisation any more, but I imagine the guys will appreciate it!

You'll need their assistance to push the new version to PyPI but that's reasonably trivial for them I believe.

**Comment by fredvisser** [comment]
Thanks for the response! I've created a [PR](https://github.com/ftpsolutions/python-third-party-license-file-generator/pull/3) with fixes for the issues I've seen on Windows. 

It's a super helpful tool, and I really appreciate the work that went into creating it. Thanks!

**Comment by lowaa** [comment]
Thanks. Version 2019.10 has been released to pypi :)
