### ISSUE TITLE
site-packages folder of virtualenv is not correctly read

### ISSUE THREAD

**Issue by mshama** [ftpsolutions/python-third-party-license-file-generator#4]
on Windows when trying to execute the script, the site-packages folder of the calling python is used and not of the python executable specified in the -p argument. 

Debugging showed that in `_run_subprocess `for windows when using `sys.executable` in `subprocess.Popen`, the `sys.path` has the value of `sys.executable` and not of the venv. I have tested using `args=command_line.split()` without `executable=sys.executable` and it worked as expected

**Comment by initialed85** [comment]
Fixed by https://github.com/ftpsolutions/python-third-party-license-file-generator/pull/9 which is now merged in- release 2020.7.18 is up on PyPI at https://pypi.org/manage/project/third-party-license-file-generator/release/2020.7.18/

Thanks all involved- will close this.
